### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by lemunozm** [lemunozm/ruscii#12]
### Changes

Create a new release containing these breaking changes

- [x] Update `Cargo.toml` with 0.4.0
- ~~#8~~
- #23
- #26
- #28
- #17
- #18 
- #29
- #32
- [x] Update changelog
- [x] Upload release and tag v0.4.0

**Comment by lemunozm** [comment]
@pumken do you have any pending changes or is it ready for the release?

**Comment by pumken** [comment]
@lemunozm I feel these changes aren't major enough for a release 0.4.0, so I want to try implementing the animation idea (#17) and fixing the dependency update PR (#18) first. I should be able to start working on those reasonably soon.

**Comment by lemunozm** [comment]
Ok, great! 🚀 No hurry at all

**Comment by lemunozm** [comment]
Thanks for your contribution to this release @pumken! 🙌🏻
