### ISSUE TITLE
Add feature: animations

### ISSUE THREAD

**Issue by pumken** [lemunozm/ruscii#17]
Quick suggestion: maybe we could provide a built-in method to have animations that might work by counting times drawn? The speed could be adjusted by the number of frames each animation stage lasts for and counting to that. It might be implemented by having an `Animation` struct that holds a `Vec` of animation stages including text, color, style, etc that tracks calls to access a stage.

I don't know, I'm just idea-dumping at the moment. Thoughts?

**Comment by lemunozm** [comment]
I remember that it was my next pending feature to add here. So it's great! Most of the projects can take advantage of this. 
I have no time right now to put into this project, but I can give support/reviews if you decide to go with it.
