### ISSUE TITLE
Ruscii animation

### ISSUE THREAD

**Issue by 0spura** [lemunozm/ruscii#37]
Hey, I'm new with rust and I'm really enjoying this experience with ruscii. Currently was added the feature "animation" and it didn't work the way I thought. Can you explain me better? I was thinking this would be a transition from x/y to another position, this way is more functional then the spaces in `text` (I think):

```rs
let animation = vec![
    AnimationFrame::new("X  ", 1),
    AnimationFrame::new(" X ", 1),
    AnimationFrame::new("  X", 1),
    AnimationFrame::new(" X ", 1),
];
```

**Comment by lemunozm** [comment]
cc @pumken

**Comment by lemunozm** [comment]
As I understand, these kinds of animations are a change in the image. In the same way, a GIF animation does not move the gif over the screen, an ASCII animation is performed in a fixed position. The idea in mind is to perform multiple ASCII changes, modifying several chars at once per frame.

If you want to make a transition, you can move `x` and `y` using the pencil. That could be another great kind of animation to build, one that uses the pencil along with coordinate transformations. By now, there is no higher abstraction for that, and you need to move the pencil manually to get that behavior.

**Comment by pumken** [comment]
Thanks for the feedback, @oluiss !

I think we can change this so that each `AnimationFrame` has a delta `Vec2` to translate the frame across the screen.

This would also work pretty well with having animations with variable height. I'll start working on this soon!

**Comment by 0spura** [comment]
Thanks @lemunozm and @pumken for the quick reply, I think I understand, if I can contribute anything you can call me.
