### ISSUE TITLE
keyboard not working

### ISSUE THREAD

**Issue by Randommist** [lemunozm/ruscii#41]
The program does not respond to key presses. I used the code from the example, and also ran the examples, but there is no reaction to pressing the Esc key or other. Keyboard layout English

**Comment by lemunozm** [comment]
Hi @Randommist, what`s your operative system?

**Comment by Randommist** [comment]
Arch Linux

**Comment by lemunozm** [comment]
You should have installed x11 libraries for your Arch Linux and run the terminal in a GUI environment, not from a TTY. If this is the case, it should work, if not, I'm a little bit lost.

**Comment by Randommist** [comment]
I have the libx11 package from pacman installed. What does it mean to run the terminal in a GUI environment? I use "cargo run --example pong". Also i use wayland

**Comment by lemunozm** [comment]
In Linux, you can run a TTY terminal without any graphic environment (in your case Wayland). `ruscii` doesn't work there. To get the "key release" event `ruscii` check the keyboard directly from the graphic environment.

Then, I do not know what can be the issue. The underlying crate to get the keyboard input is [`device_query`](https://github.com/ostrosco/device_query). The next step should be to test if that crate works fine in your OS.

**Comment by Randommist** [comment]
crate [device_query](https://github.com/ostrosco/device_query) on linux only works with X11
