### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by coder3112** [lemunozm/ruscii#46]
I really like this project. Quite simple, but can clearly do a lot with it. I only chanced upon this today, but looking over the readme, there was no mention of scope or future plans/roadmap. I know this is kind of a big commitment, but I was wondering anyways if there was a plan in the direction of development?

**Comment by lemunozm** [comment]
Hi @coder3112, I'm glad you like it!

By now, I'm in maintenance mode with this project, and there is no roadmap for it. Anyway I'm open to review contributions to make it more powerfull
