### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Darth-Ness** [lemunozm/ruscii#6]
Is there any documentation for this? I would like to make my own game with this.

**Comment by lemunozm** [comment]
Hi!

Currently, there is no API documentation or guides. I recommend checking the examples to know how it works. Of course, you can check all available API [here](https://docs.rs/ruscii/0.3.2/ruscii/), but is not documented. Sorry!

**Comment by Darth-Ness** [comment]
Ah, okay then. Do you want me to close this issue?

**Comment by lemunozm** [comment]
Don't worry, I close it.
Thanks for your question!

**Comment by Darth-Ness** [comment]
Okay thanks. Do you have plans to make a new release soon?

**Comment by lemunozm** [comment]
Currently, I'm only in maintaining mode with this crate. Maybe in the future? who knows!

**Comment by Darth-Ness** [comment]
I was wondering because the draw_filled_text function isn't available in the current releases.
